### ISSUE TITLE
The problem of nesting

### ISSUE THREAD

**Issue by chrisjpatty** [tvler/experimental-react-like-framework#2]
I hope you don't mind me opening an issue for this, but I'm truly fascinated by this idea and wanted to ask some questions. One thing I immediately thought of when I saw the example is that it does look like nice and clean for a simple set of sibling elements, but does that break down for more nested elements? 

Let's say I have something like this that one could typically do in JSX:

```jsx
<div className="app-wrapper">
  <h1>My App</h1>
  <div className="form-wrapper">
    <form>
      <fieldset disabled="true">
        <div className="label-wrapper">
          <label id="fullname">Full Name</label>
        </div>
        <div>
          <input
            type="text"
            aria-labeledBy="fullname"
            aria-describedBy="error-message"
          />
          <p className="error-message" id="error-message">
            Error Message
          </p>
        </div>
      </fieldset>
    </form>
  </div>
</div>
```

In practice there's a good argument to be made for splitting these into smaller components, but it's not untypical that a component may require a fair number of nested elements, especially when designing more complex widgets.

If I understand your proposal here this would be converted to a syntax like this:

```jsx
div({ className: "app-wrapper" }, () => {
  h1(null, "My App");
  div({ className: "form-wrapper" }, () => {
    form(null, () => {
      fieldset({}, () => {
        div({ className: "label-wrapper" }, () => {
          label(
            {
              id: "fullname",
            },
            "Full Name"
          );
        });
        div(null, () => {
          input({
            type: "text",
            "aria-labeledBy": "fullname",
            "aria-describedBy": "error-message",
          });
          p(
            { className: "error-message", id: "error-message" },
            "Error Message"
          );
        });
      });
    });
  });
});
```

In my opinion the second example may tend to be less understandable than the previous. In particular, the function calls seem sporadic, and it's difficult to tell which closing brackets belong to which element. The nesting may be a little less clear in this case. (As a note, I sent both of these examples through a default Prettier cleanup.)

That being said, I've written React for years, and I found that writing your syntax felt refreshing. Not having to deal with carets feels nice, and because it's truly "Just Javascript™️", the syntax already felt familiar. 

You've obviously thought this through quite a bit already, and I'm curious what your thoughts are on these possible syntax problems as an app gets more nested and more complicated. Is that still a good tradeoff in your opinion? One thought I had is that sufficiently advanced syntax languages for editors could dim the function calls, and highlight prop keys and values similar to how they often are in JSX. That could maybe offset some of the syntactic noise of functions.

**Comment by tvler** [comment]
Thanks for writing this up :)

> One thing I immediately thought of when I saw the example is that it does look like nice and clean for a simple set of sibling elements, but does that break down for more nested elements?

I agree with you that there is a higher initial syntax noise with deeply nested components. Tbh I'm not 100% on the current api of tag(props, children). It seems to cause a lot of noise, esp when props is null. Imagine if h1 could just be 

```ts
h1('My App')
```

or even

```ts
h1`My App`
```

However I can't think of a more resilient api than tag(props, children) as of now, it's also the same API as React.createElement too.

I think that something your example could be undervaluing is incorporating state into the ui. Something I really like about this new format is that you don't have to use brackets to go back from jsx into a javascript expression, and that conditional rendering is a lot easier. Both those things seems like they would be used pretty heavily in forms which may make the new format simpler in other ways not shown in the example.

**Comment by bebraw** [comment]
What if you went for `tag(props, children) | tag(children)` instead of `tag(props, children)`? The gotcha is that you would need a type check against a function to support the polymorphism but at the same time it would cut down some noise from the example in the issue. I am not sure if this would sit well with your implementation but it's a possible direction.

I suppose another option would be to allow `tag([children])` where you skip the function invocation and check with `Array.isArray` and then trigger the functions passed in the array.

**Comment by tvler** [comment]
Let me see if I can get the polymorphic function working well with typescript. If there aren’t any issues with that I’m fine with switching to that for now!

**Comment by bebraw** [comment]
> Let me see if I can get the polymorphic function working well with typescript. If there aren’t any issues with that I’m fine with switching to that for now!

Cool, hopefully it's just a `|` in the right spot and it will figure out the rest. 👍

**Comment by itsMapleLeaf** [comment]
I think a big part that adds to readability in JSX is the ending tags, and people overlook that a lot. It's a lot better than an unhelpful pyramid of closing brackets.

I don't think there's much that can be done on the JS side to help here, but Dart for Flutter has an extension which adds `// SomeComponent` annotations after the ending `)` for each component, so maybe something similar can be done here. Just something to keep in mind

**Comment by bebraw** [comment]
> I don't think there's much that can be done on the JS side to help here, but Dart for Flutter has an extension which adds // SomeComponent annotations after the ending ) for each component, so maybe something similar can be done here. Just something to keep in mind

Yeah, that's a cool idea.

To deal with brackets, I use a bracket coloring plugin with my editor (VS Code). It tends to help quite a bit even in regular coding.

**Comment by chrisjpatty** [comment]
Mmmm, I really like the idea of incorporating tag functions, it's made me think of a whole range of possible syntaxes:

A single child element could skip the function call potentially:
```js
div(
  h1`App Title`
)
```

Multiple elements could still be expressed without a function as an array:
```js
div([
  h1`App Title`,
  form(
    fieldset([
      label`Some Label`,
      input({type: "text"})
    ])
  )
])
```

The array example still allows for inline logic, and functions could be used for more advanced logic:
```js
const [showForm, setShowForm] = React.useState(false);

div([
  h1`App Title`,
  showForm ?
    form(
      fieldset([
        label`Some Label`,
        input({type: "text"})
      ])
    )
    : null
])
```

Anyways, you've just got me thinking now about some possibilities. Thanks again for your work on this, it's very intriguing!

**Comment by tvler** [comment]
> A single child element could skip the function call potentially

Unfortunately since all the element calls are managed by a global store, the call order of a function and the function parameter isn't enough to infer that there is a parent and child element :( We need to wrap children in a function so the child elements aren't executed initially.

**Comment by tvler** [comment]
@chrisjpatty I just made element calls polymorphic, allowing the first parameter to be children if you don't need to provide any props :)

https://github.com/tvler/experimental-react-like-framework/commit/41cdd73c30580897a4b3806e10b4d2f6c542ea66

# Before

```ts
div({ className: "app-wrapper" }, () => {
  h1(null, "My App");
  div({ className: "form-wrapper" }, () => {
    form(null, () => {
      fieldset({}, () => {
        div({ className: "label-wrapper" }, () => {
          label(
            {
              id: "fullname",
            },
            "Full Name"
          );
        });
        div(null, () => {
          input({
            type: "text",
            "aria-labeledBy": "fullname",
            "aria-describedBy": "error-message",
          });
          p(
            { className: "error-message", id: "error-message" },
            "Error Message"
          );
        });
      });
    });
  });
});
```

# After

```ts
div({ className: "app-wrapper" }, () => {
  h1("My App");
  div({ className: "form-wrapper" }, () => {
    form(() => {
      fieldset(() => {
        div({ className: "label-wrapper" }, () => {
          label({ id: "fullname" }, "Full Name");
        });
        div(() => {
          input({
            type: "text",
            "aria-labeledBy": "fullname",
            "aria-describedBy": "error-message",
          });
          p(
            { className: "error-message", id: "error-message" },
            "Error Message"
          );
        });
      });
    });
  });
});
```

**Comment by chrisjpatty** [comment]
@tvler The polymorphic function call is definitely an improvement, good call!
