### ISSUE TITLE
Looks like Flutter

### ISSUE THREAD

**Issue by shamilovtim** [tvler/experimental-react-like-framework#3]
Some people in Flutter complain about its UI language and wish Flutter would use JSX instead. It was interesting to stumble on this and see it taking the opposite approach away from JSX.

**Comment by tvler** [comment]
Yep, some comments were made about that in this issue https://github.com/tvler/experimental-react-like-framework/issues/2

Grass is always greener, haha

**Comment by shamilovtim** [comment]
careful what you wish for :DDDD

<img width="649" alt="Screen Shot 2020-07-08 at 3 47 31 PM" src="https://user-images.githubusercontent.com/3495974/86963383-6f6a8980-c132-11ea-8aa7-6ebd0af3fc3c.png">
