### ISSUE TITLE
DOM/HTML as a plain data structure

### ISSUE THREAD

**Issue by jasrusable** [tvler/experimental-react-like-framework#5]
Hey @tvler, interesting project.

I share some of the same sentiments around JSX and React as stated in your README.

IMO using a plan data structure to represent the DOM/HTML is one of the simplest and best ways to do it, the way that [hiccup](https://github.com/weavejester/hiccup) and things like [Reagent](https://reagent-project.github.io/) do it is by far the superior option IMO.

Would love to hear your thoughts :)

**Comment by tvler** [comment]
The design of this project was to allow for more standard-looking JavaScript code while building react. Things like if statements, for loops, etc :). Making elements a series of function calls felt like least confined-way to do something like that for me. 

Here’s a writeup for how apple designed the SwiftUI syntax that I feel makes a pretty good argument for not containing react templates in a data structure: https://github.com/apple/swift-evolution/blob/9992cf3c11c2d5e0ea20bee98657d93902d5b174/proposals/XXXX-function-builders.md

> - We want the programming flexibility that comes from building things up with ordinary blocks of code: the ability to have local declarations and explicit control flow.
> - We want the explicit recursive structure and implicit data flow that comes from building things up with expression operands.

**Comment by tvler** [comment]
Personally I don’t have a strong opinion on JSX, this project was just an exercise to think of a new templating design without the need for a whole new language.
